# Generated by cucumber-sinatra. (2013-09-23 16:48:39 +0100)

ENV["RACK_ENV"] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'bookmark_app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Bookmarker

class BookmarkerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BookmarkerWorld.new
end
